---
title: "Football Exploratory Analysis"
output:
  html_document: default
  html_notebook: default
---
```{r}
source("readDataToMemory.R")
readFootball()

library(ggplot2)
library(ggthemes)

print(dbListTables(sql_con))
```

## Pipes

```{r}
players %>%
  head
```

```{r}
players %>%
  colnames
```
```{r}
players %>%
  sapply(class)
class %>%
  sapply(players, .)
```



## SELECT ~ select

```{r}
players %>%
  head %>%
  select(player_name, birthday)
```

```{r}
dbGetQuery(sql_con, "
SELECT player_name
,   birthday
FROM Player
LIMIT 6
")
```

## WHERE ~ filter

```{r}
players %>%
  filter(birthday >= "1998") %>%
  head



dbGetQuery(sql_con, "
SELECT * FROM Player
WHERE birthday >='1998'; 
")





```

## ORDER ~ arrange

```{r}
players %>%
  arrange(birthday) %>%
  head
```

## aggregators ~ summarise

```{r}
players %>%
  summarise(weight=mean(weight), height=mean(height))


##con sql code


dbGetQuery(sql_con, "
SELECT AVG(weight)
,   AVG(height)
FROM Player
")
```

## mutate

```{r}
players %>%
  mutate(weight_kg = weight*0.45359237) %>%
  summarise(weight=mean(weight_kg), height=mean(height))

dbGetQuery(sql_con, "
SELECT AVG(weight)*0.45359237 AS weight
,   AVG(height) AS height
FROM Player
")

"
SELECT AVG(weight)*0.45359237 AS weight
,   AVG(height) AS height
FROM Player
" %>%
  dbGetQuery(sql_con, .)


```

## GROUP BY

```{r}
players %>%
  mutate(year=as.numeric(substring(birthday, 1, 4))) %>%
  group_by(year) %>%
  summarise(height=mean(height)) %>%
  ggplot(aes(year, height)) +
  geom_line(colour="darkorange") +
  theme_minimal()





dbGetQuery(sql_con, "
SELECT AVG(height) AS height
, substr(birthday,1,4)  AS year
FROM Player
GROUP BY year

")


"
SELECT AVG(height) AS height,
CAST(substr(birthday,1,4) AS INT) AS year
FROM Player
GROUP BY year
" %>% dbGetQuery(sql_con, .)%>% ggplot(aes(year, height)) +
  geom_line(colour="darkorange") +
  theme_minimal()


```
```{r}

"
SELECT CAST(SUBSTR(birthday,1,4) AS INT) AS year
, COUNT(1) AS n
FROM Player
GROUP BY CAST(SUBSTR(birthday,1,4) AS INT)
"%>% dbGetQuery(sql_con, .) %>%  ggplot(aes(year, n)) +
  geom_line(colour="darkorange") +
  theme_minimal()


players %>%
  mutate(year=as.numeric(substring(birthday, 1, 4))) %>%
  group_by(year) %>%
  summarise(nsample=n()) %>%
  ggplot(aes(year, nsample)) +
  geom_line(colour="darkorange") +
  theme_minimal()
```

```{r}
players %>%
  mutate(year=as.numeric(substring(birthday, 1, 4))) %>%
  group_by(year) %>%
  summarise(height=mean(height), nsamples=n()) %>%
  filter(nsamples >= 200) %>%
  ggplot(aes(year, height)) +
  geom_line(colour="darkorange") +
  theme_minimal()
```

Exercise

* Translate from SQL to dply or from dply to SQL
```{r}
dbGetQuery(sql_con, "
SELECT *
FROM Match
LIMIT 6
")
```

```{r}
dbGetQuery(sql_con, "
SELECT country_id
,   COUNT(1) AS n
FROM Match
GROUP BY country_id
ORDER BY n DESC
")
```
```{r}
countries
```


```{r}
games %>%
  left_join(countries, by=c("country_id" = "id")) %>%
  select(name, home_team_api_id) %>%
  group_by(name) %>%
  summarise(teams = n_distinct(home_team_api_id)) %>%
  arrange(desc(teams))
```

```{r}
dbGetQuery(sql_con, "
SELECT *
FROM Player_Attributes
LIMIT 6
")

```

* From where do players with higest accuracy come from?

* Add team name and translate to dplyr

```{r}
dbGetQuery(sql_con, "
SELECT stage, home_team_api_id, home_team_goal
FROM Match
WHERE country_id = 1
AND season = '2008/2009'
ORDER BY stage
")
```